sudo: true
language: rust

matrix:
    fast_finish: true
    include:
        - rust: nightly
          env: FEATURES="--features nightly"
        - rust: beta
        - rust: stable
        - rust: 1.3.0
        # verify `const fn`
        - rust: 1.31.0

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES

notifications:
    email: false
